In [5]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

#Read and show the original image
img = cv2.imread('lena.png')

cv2.imshow('Original image',img)

#Find the three color channels of the original image. OpenCV uses BGR format.
b,g,r = cv2.split(img)
#Merging BGR should be the same as the original image.
img1 = cv2.merge([b,g,r])
#Swap the value of R and B
img2 = cv2.merge([r,g,b])

#Show the original image (BGR) and processed image (RGB)
cv2.imshow('BGR image',img1) # expects true color
cv2.imshow('RGB image',img2) # expects distorted color
cv2.waitKey(0)
cv2.destroyAllWindows()
#cv2.imwrite('output\ps1-1-a-1.png',img)

True

In [5]:
b,g,r

(array([[76, 76, 77, ..., 57, 55, 54],
        [76, 76, 76, ..., 55, 56, 57],
        [76, 76, 76, ..., 56, 57, 58],
        ..., 
        [60, 64, 66, ..., 36, 35, 37],
        [63, 66, 67, ..., 36, 36, 39],
        [56, 59, 63, ..., 37, 37, 41]], dtype=uint8),
 array([[113, 113, 114, ...,  80,  77,  76],
        [113, 113, 113, ...,  77,  78,  79],
        [114, 113, 113, ...,  78,  79,  80],
        ..., 
        [ 84,  91,  93, ...,  37,  37,  39],
        [ 87,  93,  94, ...,  37,  38,  41],
        [ 80,  86,  90, ...,  38,  39,  42]], dtype=uint8),
 array([[197, 197, 198, ..., 148, 148, 147],
        [197, 197, 197, ..., 148, 149, 150],
        [196, 197, 197, ..., 149, 150, 152],
        ..., 
        [166, 172, 174, ...,  71,  71,  74],
        [169, 174, 175, ...,  71,  73,  76],
        [162, 167, 171, ...,  72,  74,  80]], dtype=uint8))

In [6]:
r,g,b

(array([[197, 197, 198, ..., 148, 148, 147],
        [197, 197, 197, ..., 148, 149, 150],
        [196, 197, 197, ..., 149, 150, 152],
        ..., 
        [166, 172, 174, ...,  71,  71,  74],
        [169, 174, 175, ...,  71,  73,  76],
        [162, 167, 171, ...,  72,  74,  80]], dtype=uint8),
 array([[113, 113, 114, ...,  80,  77,  76],
        [113, 113, 113, ...,  77,  78,  79],
        [114, 113, 113, ...,  78,  79,  80],
        ..., 
        [ 84,  91,  93, ...,  37,  37,  39],
        [ 87,  93,  94, ...,  37,  38,  41],
        [ 80,  86,  90, ...,  38,  39,  42]], dtype=uint8),
 array([[76, 76, 77, ..., 57, 55, 54],
        [76, 76, 76, ..., 55, 56, 57],
        [76, 76, 76, ..., 56, 57, 58],
        ..., 
        [60, 64, 66, ..., 36, 35, 37],
        [63, 66, 67, ..., 36, 36, 39],
        [56, 59, 63, ..., 37, 37, 41]], dtype=uint8))

In [8]:
img[:,:,:]

array([[[ 76, 113, 197],
        [ 76, 113, 197],
        [ 77, 114, 198],
        ..., 
        [ 57,  80, 148],
        [ 55,  77, 148],
        [ 54,  76, 147]],

       [[ 76, 113, 197],
        [ 76, 113, 197],
        [ 76, 113, 197],
        ..., 
        [ 55,  77, 148],
        [ 56,  78, 149],
        [ 57,  79, 150]],

       [[ 76, 114, 196],
        [ 76, 113, 197],
        [ 76, 113, 197],
        ..., 
        [ 56,  78, 149],
        [ 57,  79, 150],
        [ 58,  80, 152]],

       ..., 
       [[ 60,  84, 166],
        [ 64,  91, 172],
        [ 66,  93, 174],
        ..., 
        [ 36,  37,  71],
        [ 35,  37,  71],
        [ 37,  39,  74]],

       [[ 63,  87, 169],
        [ 66,  93, 174],
        [ 67,  94, 175],
        ..., 
        [ 36,  37,  71],
        [ 36,  38,  73],
        [ 39,  41,  76]],

       [[ 56,  80, 162],
        [ 59,  86, 167],
        [ 63,  90, 171],
        ..., 
        [ 37,  38,  72],
        [ 37,  39,  74],
        [ 41,  42,

In [393]:
img3 = img[:,:,::-1]#BRG倒序排列成RGB
cv2.imshow('RGB',img3)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [107]:
img.shape, img.size, img.dtype

((512, 512, 3), 786432, dtype('uint8'))

In [6]:
#Create a monochrome image (img1_green) 
bb = np.zeros(b.shape, dtype=np.uint8)
rr = np.zeros(r.shape, dtype=np.uint8)
image_green = cv2.merge([bb,g,rr])
cv2.imshow('Green channel',image_green)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
image_green2 = img.copy()
image_green2[:,:,0] = 0
image_green2[:,:,2] = 0
cv2.imshow('Green channel',image_green2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [157]:
img[:,:,0]

array([[76, 76, 77, ..., 57, 55, 54],
       [76, 76, 76, ..., 55, 56, 57],
       [76, 76, 76, ..., 56, 57, 58],
       ..., 
       [60, 64, 66, ..., 36, 35, 37],
       [63, 66, 67, ..., 36, 36, 39],
       [56, 59, 63, ..., 37, 37, 41]], dtype=uint8)

In [396]:
#Create a monochrome image (img1_red) 
bb = np.zeros(b.shape, dtype=np.uint8)
gg = np.zeros(g.shape, dtype=np.uint8)
image_red = cv2.merge([bb,gg,r])
cv2.imshow('Red channel',image_red)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [397]:
img_temp = img.copy()
img_temp[img.shape[0]//2-50:img.shape[0]//2+51, img.shape[1]//2-50:img.shape[1]//2+51]=\
image_green[img.shape[0]//2-50:img.shape[0]//2+51, img.shape[1]//2-50:img.shape[1]//2+51]

cv2.imshow('Replacement with green square',img_temp)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [181]:
np.max(image_green[:,:,1]), np.min(image_green[:,:,1])

(237, 0)

In [398]:
standard_deviation = np.std(image_green[:,:,1])
standard_deviation

41.048916170492099

In [399]:
mean_value = np.int(np.mean(image_green[:,:,1]))
mean_value

81

In [672]:
subtract_mean_image_temp = np.float32(image_green[:,:,1])-np.ones([512,512], dtype=np.float32)*mean_value
subtract_mean_image = subtract_mean_image_temp/standard_deviation*10+np.ones([512,512], dtype=np.uint8)*mean_value
image_green3 = image_green2.copy()
image_green3[:,:,1] = np.round(subtract_mean_image)
cv2.imshow(' ',image_green3)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [448]:
subtract_mean_image_temp/standard_deviation*10,np.round(subtract_mean_image_temp/standard_deviation*10)

(array([[  7.79557753,   7.79557753,   8.03918934, ...,  -0.2436118 ,
          -0.97444719,  -1.21805894],
        [  7.79557753,   7.79557753,   7.79557753, ...,  -0.97444719,
          -0.73083532,  -0.4872236 ],
        [  8.03918934,   7.79557753,   7.79557753, ...,  -0.73083532,
          -0.4872236 ,  -0.2436118 ],
        ..., 
        [  0.73083532,   2.43611789,   2.92334127, ..., -10.7189188 ,
         -10.7189188 , -10.23169518],
        [  1.46167064,   2.92334127,   3.16695333, ..., -10.7189188 ,
         -10.47530651,  -9.74447155],
        [ -0.2436118 ,   1.21805894,   2.19250631, ..., -10.47530651,
         -10.23169518,  -9.50086021]], dtype=float32),
 array([[  8.,   8.,   8., ...,  -0.,  -1.,  -1.],
        [  8.,   8.,   8., ...,  -1.,  -1.,  -0.],
        [  8.,   8.,   8., ...,  -1.,  -0.,  -0.],
        ..., 
        [  1.,   2.,   3., ..., -11., -11., -10.],
        [  1.,   3.,   3., ..., -11., -10., -10.],
        [ -0.,   1.,   2., ..., -10., -10., -10.]], 

In [426]:
subtract_mean_image_temp = image_green[:,:,1]-np.ones([512,512], dtype=np.uint8)*mean_value
subtract_mean_image = subtract_mean_image_temp/standard_deviation*10+np.ones([512,512], dtype=np.uint8)*mean_value
image_green3 = image_green2.copy()
image_green3[:,:,1] = np.uint8(subtract_mean_image)
cv2.imshow(' ',image_green3)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [422]:
subtract_mean_image_temp

array([[ 32,  32,  33, ..., 255, 252, 251],
       [ 32,  32,  32, ..., 252, 253, 254],
       [ 33,  32,  32, ..., 253, 254, 255],
       ..., 
       [  3,  10,  12, ..., 212, 212, 214],
       [  6,  12,  13, ..., 212, 213, 216],
       [255,   5,   9, ..., 213, 214, 217]], dtype=uint8)

In [420]:
image_green3[:,:,1]

array([[88, 88, 89, ..., 80, 80, 79],
       [88, 88, 88, ..., 80, 80, 80],
       [89, 88, 88, ..., 80, 80, 80],
       ..., 
       [81, 83, 83, ..., 70, 70, 70],
       [82, 83, 84, ..., 70, 70, 71],
       [80, 82, 83, ..., 70, 70, 71]], dtype=uint8)

In [387]:
subtract_mean_image_temp/standard_deviation*10

array([[  7.79557753,   7.79557753,   8.03918934, ...,  -0.2436118 ,
         -0.97444719,  -1.21805894],
       [  7.79557753,   7.79557753,   7.79557753, ...,  -0.97444719,
         -0.73083532,  -0.4872236 ],
       [  8.03918934,   7.79557753,   7.79557753, ...,  -0.73083532,
         -0.4872236 ,  -0.2436118 ],
       ..., 
       [  0.73083532,   2.43611789,   2.92334127, ..., -10.7189188 ,
        -10.7189188 , -10.23169518],
       [  1.46167064,   2.92334127,   3.16695333, ..., -10.7189188 ,
        -10.47530651,  -9.74447155],
       [ -0.2436118 ,   1.21805894,   2.19250631, ..., -10.47530651,
        -10.23169518,  -9.50086021]], dtype=float32)

In [386]:
np.int8(subtract_mean_image_temp/standard_deviation)

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ..., 
       [ 0,  0,  0, ..., -1, -1, -1],
       [ 0,  0,  0, ..., -1, -1,  0],
       [ 0,  0,  0, ..., -1, -1,  0]], dtype=int8)

In [382]:
kk = np.array([[1,1],[2,3]],dtype=np.uint8)
kkk = np.array([[2,2],[1,1]],dtype=np.uint8)
kk,kkk,kk-kkk

(array([[1, 1],
        [2, 3]], dtype=uint8), array([[2, 2],
        [1, 1]], dtype=uint8), array([[255, 255],
        [  1,   2]], dtype=uint8))

In [235]:
for a in kk:
    for each in a:
        if each < 0:
            each = 0
kk

array([[255,   1],
       [  2,   3]], dtype=uint8)

In [321]:
#Shift image_green to the left by 2 pixels

rows,cols = image_green2[:,:,1].shape
image_translation = image_green.copy()
M = np.float32([[1,0,-2],[0,1,0]])
image_translation[:,:,1] = cv2.warpAffine(image_translation[:,:,1],M,(cols,rows))

cv2.imshow('Shifted image',image_translation)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [341]:
image_translation[:,:,1], image_green[:,:,1]

(array([[114, 114, 115, ...,  76,   0,   0],
        [113, 113, 114, ...,  79,   0,   0],
        [113, 113, 112, ...,  80,   0,   0],
        ..., 
        [ 93,  98, 107, ...,  39,   0,   0],
        [ 94,  99, 107, ...,  41,   0,   0],
        [ 90,  99, 111, ...,  42,   0,   0]], dtype=uint8),
 array([[113, 113, 114, ...,  80,  77,  76],
        [113, 113, 113, ...,  77,  78,  79],
        [114, 113, 113, ...,  78,  79,  80],
        ..., 
        [ 84,  91,  93, ...,  37,  37,  39],
        [ 87,  93,  94, ...,  37,  38,  41],
        [ 80,  86,  90, ...,  38,  39,  42]], dtype=uint8))

In [714]:
#Subtract the shifted version of img1_green from the original img1_green
difference1 = image_translation - image_green
difference2 = np.int16(image_translation) - np.int16(image_green)
cv2.imshow('Difference1',difference1)
cv2.imshow('Difference2',difference2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [715]:
difference1[:,:,1],difference2[:,:,1]

(array([[  1,   1,   1, ..., 252, 179, 180],
        [  0,   0,   1, ...,   2, 178, 177],
        [255,   0, 255, ...,   2, 177, 176],
        ..., 
        [  9,   7,  14, ...,   2, 219, 217],
        [  7,   6,  13, ...,   4, 218, 215],
        [ 10,  13,  21, ...,   4, 217, 214]], dtype=uint8),
 array([[  1,   1,   1, ...,  -4, -77, -76],
        [  0,   0,   1, ...,   2, -78, -79],
        [ -1,   0,  -1, ...,   2, -79, -80],
        ..., 
        [  9,   7,  14, ...,   2, -37, -39],
        [  7,   6,  13, ...,   4, -38, -41],
        [ 10,  13,  21, ...,   4, -39, -42]], dtype=int16))

In [657]:
np.min(difference2[:,:,1])

-192.0

In [656]:
difference3=difference2.copy()
for r in range(difference3[:,:,1].shape[0]):
    for c in range(difference3[:,:,1].shape[1]):
        if difference3[:,:,1][r][c] < 0:
            difference3[:,:,1][r][c] = 0
cv2.imshow('Difference3',difference3)
cv2.waitKey(0)
cv2.destroyAllWindows()
np.max(difference3[:,:,1])

197.0

In [718]:
#Map min negative pixiels to 0-128 and max positive pixels to 128-255
difference4=difference2.copy()
for r in range(difference4[:,:,1].shape[0]):
    for c in range(difference4[:,:,1].shape[1]):
        if difference4[:,:,1][r][c] <= 0:
            difference4[:,:,1][r][c] = np.round(128/192*difference4[:,:,1][r][c]+128)
        else:
            difference4[:,:,1][r][c] = np.round(127/197*difference4[:,:,1][r][c]+128)

cv2.imshow('Difference4',np.uint8(difference4))
cv2.waitKey(0)
cv2.destroyAllWindows()
difference4[:,:,1],np.uint8(difference4[:,:,1])

(array([[129, 129, 129, ..., 125,  77,  77],
        [128, 128, 129, ..., 129,  76,  75],
        [127, 128, 127, ..., 129,  75,  75],
        ..., 
        [134, 133, 137, ..., 129, 103, 102],
        [133, 132, 136, ..., 131, 103, 101],
        [134, 136, 142, ..., 131, 102, 100]], dtype=int16),
 array([[129, 129, 129, ..., 125,  77,  77],
        [128, 128, 129, ..., 129,  76,  75],
        [127, 128, 127, ..., 129,  75,  75],
        ..., 
        [134, 133, 137, ..., 129, 103, 102],
        [133, 132, 136, ..., 131, 103, 101],
        [134, 136, 142, ..., 131, 102, 100]], dtype=uint8))

In [664]:
np.min(difference4[:,:,1]), np.max(difference4[:,:,1])

(0.0, 255.0)

In [668]:
np.uint8(difference4)[:,:,1]

array([[129, 129, 129, ..., 125,  77,  77],
       [128, 128, 129, ..., 129,  76,  75],
       [127, 128, 127, ..., 129,  75,  75],
       ..., 
       [134, 133, 137, ..., 129, 103, 102],
       [133, 132, 136, ..., 131, 103, 101],
       [134, 136, 142, ..., 131, 102, 100]], dtype=uint8)

In [719]:
from skimage import exposure, img_as_ubyte
imagexx=difference2.copy()
imagexx[:,:,1] = exposure.rescale_intensity(imagexx[:,:,1], out_range=(0, 2**8-1))
#img_uint8 = img_as_ubyte(imagexx)

cv2.imshow('Difference4',np.uint8(imagexx))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [713]:
np.round(imagexx[:,:,1])

array([[ 127.,  127.,  127., ...,  123.,   75.,   76.],
       [ 126.,  126.,  127., ...,  127.,   75.,   74.],
       [ 125.,  126.,  125., ...,  127.,   74.,   73.],
       ..., 
       [ 132.,  130.,  135., ...,  127.,  102.,  100.],
       [ 130.,  130.,  134., ...,  128.,  101.,   99.],
       [ 132.,  134.,  140., ...,  128.,  100.,   98.]], dtype=float32)

In [673]:
#Noise
image_noise = np.float32(img.copy())
mu, sigma = 0, 1 # mean and standard deviation
noise = np.random.normal(mu, sigma, image_noise[:,:,1].shape)

In [644]:
np.float32(noise)

array([[-0.04388357,  1.1493566 ,  0.53592342, ..., -0.05947948,
         0.41815308, -1.03651357],
       [-0.46873471, -0.19660221, -1.28478181, ..., -0.38350722,
        -1.46715534,  0.00600765],
       [-0.1258824 , -1.32959819,  1.08920598, ..., -0.30887493,
        -2.23187661,  0.72785193],
       ..., 
       [ 0.06505363, -1.02147198,  0.88629043, ..., -1.60838175,
        -0.07727242,  0.29321149],
       [-2.2026813 , -0.40648395,  1.48700464, ..., -1.60953271,
         0.18694006, -0.23314673],
       [-1.08847153,  1.24813187, -0.93315345, ...,  1.19956839,
         0.9377768 ,  1.04058373]], dtype=float32)

In [645]:
image_noise[:,:,1] = np.float32(image_noise[:,:,1])+np.float32(noise)

In [646]:
print (image_noise[:,:,1])

[[ 112.95611572  114.14935303  114.53592682 ...,   79.94052124
    77.41815186   74.96348572]
 [ 112.53126526  112.80339813  111.71521759 ...,   76.61649323
    76.53284454   79.00600433]
 [ 113.87411499  111.67040253  114.08920288 ...,   77.69112396
    76.76811981   80.72785187]
 ..., 
 [  84.06505585   89.97853088   93.8862915  ...,   35.39161682
    36.92272568   39.29321289]
 [  84.7973175    92.59351349   95.48700714 ...,   35.3904686    38.18693924
    40.76685333]
 [  78.91152954   87.2481308    89.06684875 ...,   39.1995697    39.93777847
    43.04058456]]


In [647]:
cv2.imshow('Image with noise', np.int8(image_noise))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [633]:
print (image_green[:,:,1])

[[113 113 114 ...,  80  77  76]
 [113 113 113 ...,  77  78  79]
 [114 113 113 ...,  78  79  80]
 ..., 
 [ 84  91  93 ...,  37  37  39]
 [ 87  93  94 ...,  37  38  41]
 [ 80  86  90 ...,  38  39  42]]


In [611]:
cv2.imshow('Image with noise', image_green)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [741]:
np.array(((1,2,3),(4,5,99999)), dtype=np.int_)

array([[    1,     2,     3],
       [    4,     5, 99999]])

In [748]:
np.random.random(5,4)

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [751]:
np.random.normal(50,10,(2,3))

array([[ 50.19403159,  67.03617567,  60.64022871],
       [ 36.70776912,  42.46655629,  46.85915818]])

In [756]:
a = np.random.randint(0,10,[2,3])
a

array([[2, 0, 4],
       [5, 0, 1]])

In [758]:
np.min(a,axis=1)

array([0, 0])

In [763]:
np.argmax(a,axis=1)

array([2, 0], dtype=int64)

In [26]:
list(map(lambda x: x ** 2, range(10)))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [31]:
d = {'Name' : 'Angela Merkel',
     'Country' : 'Germany',
     'Profession' : 'Chancelor',
     'Age' : 60} 
for items in d.values():
    print (items)

Angela Merkel
Germany
60
Chancelor


In [ ]:
###After adding (+/-) noise , the pixel values clips at 0, 255
img1_with_green_noise = np.int16(image1.copy())
img1_with_green_noise[:,:,1] = np.int16(img1_with_green_noise[:,:,1]) + noise
###Rescale the noised image to [0,255]
img1_with_green_noise[:,:,1] = exposure.rescale_intensity(img1_with_green_noise[:,:,1], out_range=(0, 255))
img1_with_green_noise = np.uint8(img1_with_green_noise)
cv2.imwrite('output\ps1-5-a-1.png',img1_with_green_noise)